library(shiny) # for the shiny App
library(ggplot2) # for plotting
library(gridExtra) # for arranging the plots generated by ggplot2 neatly

# code for ui.R: controls how the App looks 
shinyUI(pageWithSidebar(
  headerPanel('Visualising the Differences in Length and Width of the Petal and Sepal of Three Iris Species'),
  sidebarPanel(
    selectInput('Species', 'Select Species', as.character(unique(iris$Species)))
  ),
  mainPanel(
    plotOutput('irisplot',width = 400, height = 600)
  )
))